services:
  nginx:
    environment:
      WEB_HOST: ${WEB_HOST}
    build: .
    container_name: envault-nginx
    ports:
      - "80:80"
    networks:
      envault_network:
        ipv4_address: ${WEB_HOST}

networks:
  envault_network:
    external: true
